export { default as colors } from '@/config/colors'
export { default as companyName } from '@/config/companyName'
export { default as env } from '@/config/env'
export { default as gtm } from '@/config/gtm'
export { default as prod } from '@/config/prod'
export { default as themeColor } from '@/config/themeColor'
export { default as phoneNumber } from '@/config/phoneNumber'
