export { default as GeneralContactCTA } from '@/components/general/GeneralContactCTA'
export { default as GeneralCopyright } from '@/components/general/GeneralCopyright'
export { default as GeneralHeroDecorations } from '@/components/general/GeneralHeroDecorations'
export { default as GeneralLogo } from '@/components/general/GeneralLogo'
export { default as GeneralPopup } from '@/components/general/GeneralPopup'
export { default as GeneralSectionTitle } from '@/components/general/GeneralSectionTitle'
export { default as GeneralUIForm } from '@/components/general/GeneralUIForm'
